### ISSUE TITLE
Formulas should take parameters as well as input variables

### ISSUE THREAD

**Issue by nsmith-** [nsmith-/correctionlib#22]
For example, in schemav1 there may be several expressions that are identical up to constants:
```json
{
  "expression": "63.1722909916*(x-0.106)*(x-0.106)*(x-0.106)-26.43760378*(x-0.106)*(x-0.106)+3.68804572731*(x-0.106)+1.1499707698822021",
  "parser": "TFormula",
  "parameters": [4]
}
```

It would be more efficient to store the constants and formula separately, filling in the literals on evaluation. In v2 draft (see #19 ) we renamed parameters to variables (x, y, z, t) and introduced parameters. We could then have:
```json
{
  "nodetype": "formula",
  "expression": "[0]*(x-[4])*(x-[4])*(x-[4])-[1]*(x-[4])*(x-[4])+[2]*(x-[4])+[3]",
  "parser": "TFormula_v1",
  "parameters": [63.1722909916, 26.43760378, 3.68804572731, 1.1499707698822021, 0.106],
  "variables": ["discriminant"]
}
```
This is already in line with how JEC are distributed. BTV corrections could also take advantage of this with some modification.

One additional performance benefit that can be realized is to parse the expression once (mildly expensive). To do this, we could introduce a formularef nodetype that references a fixed formula contained in the top-level correction object. For example, we might then have:
```json
{
  "nodetype": "formularef",
  "parameters": [63.1722909916, 26.43760378, 3.68804572731, 1.1499707698822021, 0.106],
}
```
where the remaining information is held in the formula at top level. I think having multiple classes of formulas in such a scheme is probably overkill since anyway one can specify formulas individually as before if there are several classes.

**Comment by nsmith-** [comment]
#19 implements the first half of this discussion. What remains is `formularef`. It would be nice to get some feedback from BTV if they think they can adopt the style for their formulas and whether there would be a need to reference multiple formulas or not. FYI @XavierAtCERN @kirschen

**Comment by kirschen** [comment]
Hi all, 
I tried the current master branch version for another try at the JEC txt-->JSON conversion and it works as expected, thanks! 
Speaking from the perspective of JEC, the `formularef` seems the way to go, because there are corrections with e.g. 2500 bins in single txt-files, all with the same formula. If there is some performance gain from parsing the formula just once then JEC will definitely profit a lot.

**Comment by nsmith-** [comment]
Thanks @kirschen for the update! I think then it only remains to decide if just one `formularef` target per correction is acceptable or not (keeping in mind that individual formula objects will continue to be supported). Pinging @XavierAtCERN as BTV is currently the other main formula user.

**Comment by nsmith-** [comment]
I looked at one btag file and counted the number of independent formulas:
```python
df = pd.read_csv("DeepCSV_102XSF_V1.btag.csv.gz")
# a crude regex to match any constant
df.groupby(df[" formula "].str.replace(re.compile("((?<=[\+(])-|)\d+(\.\d*|)(e-?\d+|)"), "C")).size()
```
and got:
```
 formula
 "(C*((C+(C*x))/(C+(C*x))))+C"                            54
 "(C*((C+(C*x))/(C+(C*x))))-C"                            54
 "(C+(C*(log(x+C)*(log(x+C)*(C-(C*log(x+C)))))))+C"       54
 "(C+C*x+C*x*x+C*x*x*x)*(C+(C))"                           2
 "(C+C*x+C*x*x+C*x*x*x)*(C+(C+C*x+C*x*x))"                 4
 "(C+C*x+C*x*x+C*x*x*x)*(C-(C))"                           2
 "(C+C*x+C*x*x+C*x*x*x)*(C-(C+C*x+C*x*x))"                 4
 "(C+C/sqrt(x))*(C+(C))"                                   1
 "(C+C/sqrt(x))*(C+(C+C*x+C*x*x))"                         2
 "(C+C/sqrt(x))*(C-(C))"                                   1
 "(C+C/sqrt(x))*(C-(C+C*x+C*x*x))"                         2
 "C*((C+(C*x))/(C+(C*x)))"                                 6
 "C+((C*(log(x+C)*(log(x+C)*(C-(C*log(x+C))))))-C)"       54
 "C+(C*(log(x+C)*(log(x+C)*(C-(C*log(x+C))))))"            6
 "C+C*x+C*x*x+C*x*x*x"                                     2
 "C+C/sqrt(x)"                                             1
 (C+C*x)                                                5475
 C+x*(C+x*(C+x*(C+x*(C+x*(C+x*-C)))))                    209
 C+x*(C+x*(C+x*(C+x*(C+x*(C+x*C)))))                     619
dtype: int64
```
So it seems there is no regular BTag formula. Given the multiplicity, I'll implement multiple formularef targets.

Correction will get a new optional:
```python
class Correction(Model):
    # ...
    generic_formulas: Optional[List[Formula]]
```
and there will be a new content node:
```python
class FormulaRef(Model):
    nodetype: Literal["formularef"]
    index: int
    "Indexes the Correction.generic_formulas list"
    parameters: List[float]
```
