### ISSUE TITLE
(Input) variable mappings/transforms

### ISSUE THREAD

**Issue by IzaakWN** [nsmith-/correctionlib#3]
It might be nice to have some way of defining a mapping or transformation of (input) variables. This could, prevent making duplicate data, allow for intermediate computations, and cover special cases. For example:
- An input might be `eta`, but the output is actually binned in abs(eta).
- Some values of enumerated/bit-wise input variable map onto the same output, e.g. the TauPOG/HTT group uses the `genmatch` variable, a.k.a. [`Tau_genPartFlav` in nanoAOD](https://cms-nanoaod-integration.web.cern.ch/integration/master-106X/mc102X_doc.html#Tau), and the same [e → 𝜏h fake rate SFs](https://github.com/IzaakWN/correctionlib/tree/TauPOG/data/tau#structure-e---tau-fake-rate-sf) are used for `genmatch==1` and `genmatch==3`. In this case make a simple map from `genmatch` to some key or enumerator to point to the same SF. Otherwise the JSON should contain the same `Content` block for `genmatch==1` and `genmatch==3` separately, _or_ the user has to construct the right category key/flag.

Note this would also allow for backwards compatibility if, for example, an eta-dependent SF output was initially binned in `abs(eta)`, but later split in backward/forward `eta`.

My idea would be to add some new, optional "mapping" and/or "transformation" block in the scheme, something like
```
{
  'version': 0,
  'name':    "test",
  'inputs': [
    {'name': "eta", 'type': "real", 'description': "tau eta"},
    {'name': "pt",  'type': "real", 'description': "tau pt"},
    {'name': "genmatch",  'type': "int", 'description': "genmatch"},
  ],
  'maps': [
    { 'name': "abseta", 'type': "real",
      "form": "abs(eta)"
    },
    { 'name': "genmatchkey", 'type': "string",
      "form": "'electron': [1,3], 'muon': [2,4], 'tau': [5], 'jet': [0,6,'*']"
    },
  ]
  'output': {'name': "weight", 'type': "real"},
  'data': { ... },
}
```
where you can have a functional transformation, or a simple mapping between ints, floats and/or strings. This would create new variables that can be used down the line to evaluate other functions, binning, categories, etc.

**Comment by nsmith-** [comment]
If I recall, there was some interest in exposing things like abs(eta) to the user in the Tau POG meeting. I think this is still a good idea, but might ask for more input.

**Comment by nsmith-** [comment]
Each transform is in principle a 1-argument correction, so it could be any `Content` node. Perhaps `Correction` can have an new field `transforms: Optional[Transform]` where:
```python
class Transform:
    input: Variable
    output: Variable
    data: Content
```
and each output is appended to the nominal input list for the correction. The constraints would be that the output needs to have a different name than any input and may need to be restricted to double type depending on the outcome of #12 .

**Comment by nsmith-** [comment]
This can also solve an issue with JEC formula clamping discussed in https://github.com/nsmith-/correctionlib/discussions/21#discussioncomment-407143. I think that might be enough support to make it a v2 item.

**Comment by IzaakWN** [comment]
Hi @nsmith-, many thanks for implementing this with PR https://github.com/cms-nanoAOD/correctionlib/pull/47! It is really nice that `Transform.rule` can take any `Content` object, so it is very versatile. Can you confirm that the following way would be the best way to do it if you would like to map `eta` onto `abs(eta)` for a simple 1D histogram, please? It seems to work as expected.
```
corr = Correction.parse_obj({
  'version': 0,
  'name': "test_hist1D",
  'description': "Simple 1D SF",
  'inputs': [
    {'name': "eta", 'type': "real", 'description': "tau eta"},
  ],
  'output': {'name': "weight", 'type': "real"},
  'data': {
    'nodetype': "transform",
    'input': "eta",
    'rule': {
      'nodetype': 'formula',
      'expression': "abs(x)",
      'parser': "TFormula",
      'variables': ["eta"],
    },
    'content': {
      'nodetype': "binning",
      'input': "eta",
      'edges': xbins,
      'flow': "error",
      'content': sfs,
    },
  },
})
```

**Comment by nsmith-** [comment]
Yep that looks correct.
