### ISSUE TITLE
Issue with formula evaluator

### ISSUE THREAD

**Issue by kirschen** [nsmith-/correctionlib#40]
**Problem:**
The formula is not properly parsed, looks like the parameterization with snippets of the form ("x<10 + x>=10") is not covered by the grammar, yet.

**Offending files/formula**
Formula:
```max(0.0001,((x<10)*([9]))+((x>=10)*([0]+([1]/(pow(log10(x),2)+[2]))+([3]*exp(-([4]*((log10(x)-[5])*(log10(x)-[5])))))+([6]*exp(-([7]*((log10(x)-[8])*(log10(x)-[8]))))))))```

Source txt-file:
https://github.com/cms-jet/JECDatabase/blob/master/textFiles/Summer19UL16APV_V2_MC/Summer19UL16APV_V2_MC_L2Relative_AK4PFchs.txt

Converted JSON (with .txt added at the end)
[Summer19UL16APV_V2_MC_L2Relative_AK4PFchs.txt.json.txt](https://github.com/nsmith-/correctionlib/files/6050061/Summer19UL16APV_V2_MC_L2Relative_AK4PFchs.txt.json.txt)

**Error message:**
```
kirschen@lxplus771 src $ python3 testJECJSON.py Summer19UL16APV_V2_MC_L2Relative_AK4PFchs.txt                                                                                                                                                                                 
['JetEta', 'JetPt']
Traceback (most recent call last):
  File "testJECJSON.py", line 44, in <module>
    cset = core.CorrectionSet.from_file(inputJSON)
RuntimeError: Failed to parse Formula expression at position 33:
max(0.0001,((max(min(x,[1]),[0])<10)*([11]))+((max(min(x,[1]),[0])>=10)*([2]+([3]/(pow(log10(max(min(x,[1]),[0])),2)+[4]))+([5]*exp(-([6]*((log10(max(min(x,[1]),[0]))-[7])*(log10(max(min(x,[1]),[0]))-[7])))))+([8]*exp(-([9]*((log10(max(min(x,[1]),[0]))-[10])*(log10(max(min(x,[1]),[0]))-[10]))))))))
                                 ^
syntax error, unexpected '<', expecting <BINARYOP>, <CALLB>.
```

**Comment by nsmith-** [comment]
Do you know why this `(x < a)*b + (x >= a)*c` form is used instead of a ternary (e.g. `(x < a) ? b : c`) ? Granted, ternaries aren't supported by the grammar yet either. My initial reaction is the ternary would be better performed by a parent node but I can imagine situations (ternary on a derived quantity) where that's not possible.

**Comment by kirschen** [comment]
Not sure how that parametrisation came about. The ternary would appear more readable to me. Not sure whether the reco::FormulaEvaluator supports it?

**Comment by nsmith-** [comment]
I'd let @dr15jones confirm, but it looks to me that the `reco::FormulaEvaluator` doesn't support ternaries. We could add them here, as they are supported in ROOT. Thoughts?
