### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by IzaakWN** [nsmith-/correctionlib#7]
As of now, [`schemav1.py`](https://github.com/nsmith-/correctionlib/blob/master/correctionlib/schemav1.py) only works for python version 3.8 or higher. The python versions in the CMSSW releases I checked are mostly 3.6, so it might be worth making this code compatible with 3.6 so workflows do not need to be separated.

Before 3.8, `typing.ForwardRef` was private and [`typing.Literal`](https://docs.python.org/3/library/typing.html#typing.Literal) did not exist. The former one can solve with
```
try: # python 3.8
  from typing import ForwardRef
except ImportError: # private in python 3.6 and 3.7
  from typing import _ForwardRef as ForwardRef
```
but `typing.Literal` might need to be replace with something else if we want compatibility with 3.6.

It might also be useful for new users to add a warning on top of this script:
```
import sys; assert sys.version_info>=(3,8),"Python version must be newer than 3.8, currently %s.%s"%(sys.version_info[:2])
```

**Comment by nsmith-** [comment]
Per pydantic docs, `Literal` is supported prior to python 3.8 via https://pypi.org/project/typing-extensions/
For ForwardRef, it looks like pydantic is also happy to take strings in lieu of types so I'll just move to that
